---
- name: Get Cilium CLI stable version
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
    return_content: yes
  register: cilium_cli_version

- name: Set CLI architecture
  ansible.builtin.set_fact:
    cli_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Override CLI architecture for arm64
  ansible.builtin.set_fact:
    cli_arch: "arm64"
  when: ansible_architecture == "aarch64"

- name: Download Cilium CLI tarball and sha256sum
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content | trim }}/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    force: true
  loop:
    - ""
    - ".sha256sum"

- name: Verify Cilium CLI tarball
  ansible.builtin.shell:
    cmd: "sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    chdir: "/tmp"
  ignore_errors: yes
  register: sha256sum_check

- name: Extract Cilium CLI tarball
  ansible.builtin.unarchive:
    src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
  when: sha256sum_check.rc == 0

- name: Remove Cilium CLI tarball and sha256sum file
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    state: absent
  loop:
    - ""
    - ".sha256sum"
